import os
from datetime import datetime
from typing import Any

import markdown

from src.domain.ports import ReportingPort


class ReportGeneratorAdapter(ReportingPort):
    """
    Generates a Daily Recommendation report in MD and HTML formats.
    """

    def __init__(self, output_dir: str = "docs/reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_daily_report(
        self,
        recommendations: list[dict[str, Any]],
        portfolio_value: float = 100.0,
        liquid_cash: float = 0.0,
        risk_reserve: float = 0.0,
        strat_name: str = "N/A",
        strat_description: str = "N/A",
        gain_loss_pct: float = 0.0,
        gain_loss_abs: float = 0.0,
        watchlist: list[str] | None = None,
        investor_moves: list[str] | None = None,
        world_events: list[str] | None = None,
    ) -> str:
        """
        Creates MD and HTML reports. Returns the path to the HTML version.
        """
        today = datetime.now().strftime("%Y-%m-%d")
        md_path = os.path.join(self.output_dir, f"report_{today}.md")
        html_path = os.path.join(self.output_dir, f"report_{today}.html")

        # --- Generate Markdown ---
        md_content = f"# 🚀 Billion Dollar Journey ({today})\n\n"
        md_content += "## 📈 Portfolio Performance\n"
        md_content += f"**Current Total Value:** ${portfolio_value:,.2f}\n"
        md_content += f"**Liquid Cash:** ${liquid_cash:,.2f}\n"
        md_content += f"**Risk Protected Reserve:** ${risk_reserve:,.2f}\n"
        md_content += f"**Deployable Capital:** ${max(0, liquid_cash - risk_reserve):,.2f}\n"
        sign = "+" if gain_loss_abs >= 0 else ""
        md_content += f"**Cumulative Gain/Loss:** {sign}${gain_loss_abs:,.2f} ({sign}{gain_loss_pct:.2f}%)\n\n"
        md_content += f"## 💡 Strategy Sentiment: {strat_name}\n{strat_description}\n\n"

        md_content += "## 📊 Executive Summary (Action Now)\n"
        md_content += "| Symbol | Company Name | Action | Quantity | Price | Est. Total |\n"
        md_content += "| :--- | :--- | :--- | :--- | :--- | :--- |\n"

        summary_total = 0.0
        immediate_moves = [r for r in recommendations if r.get("timing") == "IMMEDIATE"]
        consolidated: dict[str, dict[str, Any]] = {}
        for r in immediate_moves:
            key = f"{r['symbol']}_{r['action']}"
            if key not in consolidated:
                consolidated[key] = {
                    "symbol": r["symbol"],
                    "name": r.get("company_name", "N/A"),
                    "action": r["action"],
                    "quantity": 0.0,
                    "price": r.get("price", 0.0),
                }
            consolidated[key]["quantity"] += r.get("quantity", 0.0)

        if not consolidated:
            md_content += "| **No immediate actions** | | | | | |\n"
        else:
            for _, c in consolidated.items():
                line_total = c["quantity"] * c["price"]
                summary_total += line_total
                md_content += f"| **{c['symbol']}** | {c['name']} | {c['action']} | {c['quantity']:.4f} | ${c['price']:.2f} | **${line_total:,.2f}** |\n"

        md_content += f"| **TOTAL** | | | | | **${summary_total:,.2f}** |\n\n"

        md_content += "## 👁️ Universe Watchlist\n"
        if watchlist:
            for item in watchlist:
                md_content += f"- {item}\n"
        else:
            md_content += "- No new watchers.\n"

        md_content += "\n## 🧠 Intelligence Correlation\n### 🏛️ Elite Investor Moves\n"
        if investor_moves:
            for move in investor_moves:
                md_content += f"- {move}\n"
        else:
            md_content += "- No moves detected.\n"

        md_content += "\n### 🌍 Notable World Events\n"
        if world_events:
            for event in world_events:
                md_content += f"- {event}\n"
        else:
            md_content += "- No high-impact events.\n"

        md_content += "\n---\n*This report is generated by the fintrdr Agent Framework.*"

        # Save MD
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        # --- Generate HTML ---
        css = """
        <style>
            body { font-family: sans-serif; line-height: 1.6; max-width: 900px; margin: 40px auto; padding: 20px; background: #f4f7f6; }
            h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
            h2 { color: #2980b9; margin-top: 30px; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 0 20px rgba(0,0,0,0.1); }
            th, td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #ddd; }
            th { background-color: #3498db; color: white; }
            tr:hover { background-color: #f5f5f5; }
            .gain { color: #27ae60; font-weight: bold; }
            .loss { color: #e74c3c; font-weight: bold; }
        </style>
        """
        html_body = markdown.markdown(md_content, extensions=["tables"])
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(
                f"<!DOCTYPE html><html><head><title>fintrdr Report</title>{css}</head><body>{html_body}</body></html>"
            )

        return html_path
